---
- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!!"

- name: Show info about DB host internal IP
  debug:
    msg: "DB host internal IP is {{ db_host }}"

- include: ruby.yml
- include: puma.yml
