---
- name: Configure app hosts
  hosts: all
  become: true

  tasks:
    - set_fact: db_host="{{ ansible_default_ipv4.address }}"
      delegate_to: "{{ item }}"
      with_items: "{{ play_hosts }}"
      delegate_facts: True
      when: "'db' in inventory_hostname"

    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma
      when: "'app' in inventory_hostname"

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config
        owner: appuser
        group: appuser
      notify: reload puma
      when: "'app' in inventory_hostname"

    - name: Enable Puma
      systemd: name=puma enabled=yes
      when: "'app' in inventory_hostname"

  handlers:
    - name: reload puma
      systemd: name=puma state=restarted
