---
- name: Install app requirements
  hosts: all
  become: true

  vars:
    packages:
    - ruby-full
    - ruby-bundler
    - build-essential

  tasks:
    - name: Install a list of packages
      apt:
        name: "{{ packages }}"
        update_cache: yes
